#pragma once
namespace Engine
{
#define DECLARE_TAG(a, b) \
    static constexpr const char* a = #b; \
    static constexpr const _string_id ID##a = STRID(#b);

	//DECLARE_TAG(TAG_RES_VIBUFFER_QUADCOL, VIBUFFER_QUADCOL)
	//DECLARE_TAG(TAG_RES_VIBUFFER_QUADTEX, VIBUFFER_QUADTEX)
	//DECLARE_TAG(TAG_RES_CBUFFER, CBUFFER);
	//DECLARE_TAG(TAG_RES_FMOD_SOUND, FMOD_SOUND);
	//DECLARE_TAG(TAG_RES_JSON, JSON);
	//DECLARE_TAG(TAG_RES_VERTEX_SHADER, VERTEX_SHADER);
	//DECLARE_TAG(TAG_RES_PIXEL_SHADER, PIXEL_SHADER);

	
}